### ISSUE TITLE
Checking in compilation outputs.

### ISSUE THREAD

**Issue by gigadude** [TooTallNate/node-gyp#606]
I'm in a corporate setting where it makes sense to check in the compiled binaries so people can just use scripts without needing a build environment, but this currently limits me to supporting a single version of node and a single platform. I'd like to be able to specify that products should go into `build/<nodeversion>/<platform>/Release/...` etc, are there any good examples of how to tweak the bindings to support this?

**Comment by justinmchase** [comment]
I would recommend reconsidering this approach. 

For one thing checking binaries into source control can end up creating very large code repositories and end up bogging you down considerably. 

For another thing the happy path with node/npm is to check in just the source code for your native addons and each developer will build the module when they run `npm install`. The development environments for this shouldn't be too hard to setup, and presumably everyone is a developer so I don't see why you wouldn't do this.

The only reasonable alternative I've found is [node-pre-gyp](https://www.npmjs.com/package/node-pre-gyp). Where you would build the binaries and publish the results to an accessible location and `node-pre-gyp` would pull those down instead of building locally. If you do this you will definitely want to control the version of nodejs that everyone is using and you'll need to build your modules on every platform you support. This is a little bit harder to setup continuous integration for but it has a huge payoff in compilation times. 

If you use iojs instead of node you can use this handy repo for getting specific versions:
https://github.com/coolaj86/iojs-install-script

It may seem easier to "just check in the binaries" but in my experience, it can end up being expensive to go that route in the long run.

**Comment by gigadude** [comment]
In my case it makes sense to do do, I'm able to control the execution environment (node version etc.) and not every person who might want to use the scripts has a full build environment pulled. Thanks for the link to node-pre-gyp, looks like it might be what I'm looking for...

**Comment by TooTallNate** [comment]
I also wrote [`node-bindings`](https://github.com/TooTallNate/node-bindings) with the idea of precompiled binaries inside the module, but it's a lot of work to maintain precompiled binaries, and in general I don't do it anymore.
